image: maven:3.3.9-jdk-8

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

stages:
  - publication
  - upload

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${CI_PROJECT_DIR}/target


publication:
  timeout: 2m
  retry: 1
  stage: publication
  only:
    - main
  script:
    - 'mvn deploy -T 1C -am -Dmaven.test.skip -s ci_settings.xml'


upload:
  timeout: 1m
  retry: 2
  stage: upload
  needs:
    - 'publication'
  only:
    - main
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$ARCHANGEL_SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $ARCHANGEL_PORT $ARCHANGEL_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'scp -P $ARCHANGEL_PORT target/plazmix-api-1.12.jar $ARCHANGEL_USER@$ARCHANGEL_HOST:~/cloud/templates/dependency/api-1.12/plugins'
