package net.plazmix.game.item.menu;

import lombok.NonNull;
import net.plazmix.game.item.GameItem;
import net.plazmix.game.item.GameItemsCategory;
import net.plazmix.game.user.GameUser;
import net.plazmix.inventory.impl.BaseSimpleInventory;
import net.plazmix.utility.ItemUtil;
import net.plazmix.utility.NumberUtil;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

public class GameCategoriesAutoGeneratedMenu extends BaseSimpleInventory {

    public GameCategoriesAutoGeneratedMenu(int inventoryRows, String inventoryTitle) {
        super(inventoryTitle, inventoryRows);
    }

    @Override
    public void drawInventory(Player player) {
        GameUser gameUser = GameUser.from(player);
        GameUser.getService().getGameItemCategoriesMap().valueCollection().forEach(itemsCategory ->

                setClickItem(itemsCategory.getInventorySlot(), toBukkitItem(itemsCategory, gameUser), (player1, event) ->
                        new GameItemsAutoGeneratedMenu(inventoryRows, itemsCategory.getCategoryName(), itemsCategory, this).openInventory(player)));
    }

    public ItemStack toBukkitItem(@NonNull GameItemsCategory itemsCategory, @NonNull GameUser gameUser) {
        int boughtItemCount = gameUser.getGameItems(itemsCategory).size();
        int selectedItemsCount = gameUser.getSelectedItems(itemsCategory).size();

        GameItem selectedItem = gameUser.getSelectedItem(itemsCategory);

        return ItemUtil.newBuilder(itemsCategory.getIconStack())
                .setName(ChatColor.YELLOW + itemsCategory.getCategoryName())

                .addLore("")
                .addLoreArray(itemsCategory.getDescription() != null ? itemsCategory.getDescription().toArray(new String[0]) : new String[0])

                .addLore("")
                .addLore("§7Открыто: §8(§e" + boughtItemCount + " §7из §e" + itemsCategory.getMappedItemsCount() + "§8) §6"
                        + NumberUtil.getIntPercent(boughtItemCount, itemsCategory.getMappedItemsCount()) + "%")

                .addLore(selectedItemsCount <= 1
                        ? (selectedItem != null ? "§7Выбрано: §a" + selectedItem.getItemName() : "§cНичего не выбрано")
                        : "§7Выбрано §a" + NumberUtil.formattingSpaced(selectedItemsCount, "§7предмет", "§7предмета", "§7предметов"))

                .addLore("")
                .addLore("§e▸ Нажмите, чтобы открыть!")

                .setGlowing(selectedItem != null)
                .build();
    }

}
