name: ${project.name}
main: net.plazmix.PlazmixApiPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: ItzStonlex

depend: [ProtocolLib, CoreConnector]
