package net.plazmix.game.item;

import lombok.NonNull;
import net.plazmix.game.item.menu.GameItemsAutoGeneratedMenu;
import net.plazmix.game.mysql.GameMysqlDatabase;
import net.plazmix.game.user.GameUser;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;

public interface GameItemParameter {

    GameItem getItem();
    GameMysqlDatabase getDatabase();

    ItemStack toBukkitItem(
            @NonNull GameUser gameUser,
            @NonNull GameItemsCategory categoryFor
    );

    void onGeneratedInventoryAction(
            @NonNull GameUser gameUser,
            @NonNull GameItemsAutoGeneratedMenu menu,
            @NonNull InventoryClickEvent event,
            @NonNull GameItemsCategory categoryFor
    );

    void onDefaultApply(
            @NonNull GameUser gameUser
    );

    void onDefaultCancel(
            @NonNull GameUser gameUser
    );

    void onDefaultSelect(
            @NonNull GameUser gameUser
    );

    void onDefaultUnselect(
            @NonNull GameUser gameUser
    );

    void onDefaultPurchased(
            @NonNull GameUser gameUser
    );

}
